M48
; DRILL file {KiCad 7.0.1} date Fri Oct 27 08:58:36 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-27T08:58:36+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
%
G90
G05
T1
X4.0335Y-2.8425
X4.2264Y-2.8425
T2
X2.5Y-1.7126
X2.5Y-3.0118
X4.3898Y-2.0472
X4.3898Y-2.5984
T0
M30
